# Generated by Django 5.2.6 on 2025-09-19 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('condition', models.CharField(choices=[('new', 'ของใหม่'), ('used', 'มือสอง')], default='used', max_length=10, verbose_name='สภาพสินค้า')),
                ('status', models.CharField(choices=[('pending', 'รอการอนุมัติ'), ('active', 'กำลังขาย'), ('sold', 'ขายแล้ว'), ('rejected', 'ถูกปฏิเสธ')], default='pending', max_length=10, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขาย')),
            ],
        ),
    ]
