# Generated by Django 5.2.6 on 2025-11-21 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='ชื่อที่แสดง')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='รูปโปรไฟล์')),
                ('promptpay_qr', models.ImageField(blank=True, null=True, upload_to='payment_qr/', verbose_name='QR Code PromptPay')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='ธนาคาร')),
                ('account_number', models.CharField(blank=True, max_length=20, verbose_name='เลขที่บัญชี')),
                ('account_name', models.CharField(blank=True, max_length=100, verbose_name='ชื่อบัญชี')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
