# Generated by Django 5.2.6 on 2025-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='📦', max_length=10, verbose_name='ไอคอน/Emoji'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', '✨ มือหนึ่ง (New)'), ('used', '📦 มือสอง (Used)')], default='used', max_length=10, verbose_name='สภาพสินค้า'),
        ),
    ]
