# Generated by Django 5.2.6 on 2026-01-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_userreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='promptpay_qr',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
