# Generated by Django 5.2.6 on 2026-01-19 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'สแปม / โฆษณา'), ('fake', 'สินค้าปลอม / ลอกเลียนแบบ'), ('prohibited', 'สินค้าผิดกฎหมาย'), ('harassment', 'พฤติกรรมไม่เหมาะสม / คุกคาม'), ('fraud', 'ฉ้อโกง / หลอกลวง'), ('bug', 'แจ้งปัญหาการใช้งานเว็บไซต์'), ('other', 'อื่นๆ')], default='other', max_length=20)),
                ('details', models.TextField(blank=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('resolved', 'แก้ไขแล้ว'), ('ignored', 'ปฏิเสธ/ยกเลิก')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='products.product')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
