# Generated by Django 5.2.6 on 2026-01-20 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'รายงานปัญหา', 'verbose_name_plural': 'รายการแจ้งปัญหา (Reports)'},
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่แจ้ง'),
        ),
        migrations.AlterField(
            model_name='report',
            name='details',
            field=models.TextField(verbose_name='รายละเอียดเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='report',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='สินค้าที่เกี่ยวข้อง'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('bug', '🐛 แจ้งปัญหาเว็บไซต์ / บั๊ก'), ('fraud', '💸 หลอกลวง / ฉ้อโกง'), ('fake', '❌ สินค้าปลอม / ลอกเลียนแบบ'), ('harassment', '🤬 คำหยาบคาย / คุกคาม'), ('spam', '📢 สแปม / โฆษณา'), ('other', '📝 อื่นๆ')], default='other', max_length=20, verbose_name='หัวข้อปัญหา'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้ที่ถูกรายงาน'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แจ้ง'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ รอตรวจสอบ'), ('investigating', '🔍 กำลังตรวจสอบ'), ('resolved', '✅ แก้ไขแล้ว'), ('ignored', '❌ ปฏิเสธ/ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ'),
        ),
    ]
