# Generated by Django 5.2.6 on 2026-01-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_report_options_alter_report_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'รายงานปัญหา', 'verbose_name_plural': 'รายการแจ้งปัญหา (Reports)'},
        ),
        migrations.AddField(
            model_name='report',
            name='evidence_image',
            field=models.ImageField(blank=True, null=True, upload_to='report_evidence/', verbose_name='รูปประกอบ/หลักฐาน'),
        ),
    ]
