# Generated by Django 5.2.6 on 2026-01-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_report_options_report_evidence_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='contact_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อ/เบอร์ติดต่อกลับ (Optional)'),
        ),
    ]
