# Generated by Django 5.2.6 on 2026-01-22 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_report_contact_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='evidence_image',
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_evidence/', verbose_name='รูปหลักฐาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.report')),
            ],
        ),
    ]
